board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "board"

urlpatterns = [
    path("flux/", views.display_flux, name="flux"),
    path("posts/", views.display_posts, name="posts"),
    path("review/", views.create_review, name="review"),
    path("comment/<str:ticket_id>", views.add_comment, name="comment"),
    path("delete_review/<str:review_id>", views.delete_review, name="delete_review"),
    path("update_review/<str:review_id>", views.update_review, name="update_review"),
    path("ticket/", views.create_ticket, name="ticket"),
    path("update_ticket/<str:ticket_id>", views.update_ticket, name="update_ticket"),
    path("delete_ticket/<str:ticket_id>", views.delete_ticket, name="delete_ticket"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

follow/urls.py
from django.urls import path

from . import views

app_name = "follow"


urlpatterns = [
    path("", views.followup, name="follow"),
    path("unfollow/<user_to_unfollow>", views.unfollow, name="unfollow"),
]

litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("login.urls")),
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("board/follow/", include("follow.urls")),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views


app_name = "login"

urlpatterns = [
    path("", views.signin, name="index"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logOut, name="logout"),
]

board/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="", verbose_name="img")
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.headline}, {self.user}"

board/forms.py
from django import forms
from .models import Ticket, Review


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ["title", "description", "image"]
        labels = {
            "title": "Titre du livre",
            "description": "Résumé du livre",
            "image": "Image de couverture",
        }
        widgets = {"description": forms.Textarea(attrs={"rows": 4})}


class ReviewForm(forms.ModelForm):
    CHOICES = [
        ("0", "0"),
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
    ]
    rating = forms.ChoiceField(
        choices=CHOICES, widget=forms.RadioSelect(), label="Note"
    )

    class Meta:
        model = Review
        fields = ["headline", "rating", "body"]
        labels = {"headline": "Avi général", "body": "Commentaire"}
        widgets = {"body": forms.Textarea(attrs={"rows": 4})}

board/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import TicketForm, ReviewForm
from .models import Ticket, Review
from follow.models import UserFollows


@login_required
def display_flux(request):
    """Display tickets and reviews from the following accounts."""
    users = [
        followed.followed_user
        for followed in UserFollows.objects.filter(user=request.user)
    ]
    users.append(request.user)
    tickets = (
        Ticket.objects.filter(user__in=users)
        # .exclude(user=request.user) affiche uniquement les posts des autres users
        .order_by("-time_created")
    )
    return render(request, "flux.html", {"tickets": tickets})


@login_required
def display_posts(request):
    """Display our tickets or reviews."""
    tickets = Ticket.objects.filter(user=request.user).order_by("-time_created")
    return render(request, "posts.html", {"tickets": tickets})


@login_required
def create_ticket(request):
    """Create ticket to request a review."""
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect("board:posts")
    else:
        form = TicketForm()
    context = {"form": form}
    return render(request, "ticket.html", context)


@login_required
def delete_ticket(request, ticket_id):
    """Delete a ticket."""
    ticket = Ticket.objects.get(id=ticket_id)
    if request.user == ticket.user:
        ticket.delete()
    return redirect("board:posts")


@login_required
def update_ticket(request, ticket_id):
    """Update a ticket."""
    instance_ticket = Ticket.objects.get(id=ticket_id)
    if request.method == "POST":
        form = TicketForm(request.POST, request.FILES, instance=instance_ticket)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect("board:posts")
    else:
        form = TicketForm(instance=instance_ticket)
    context = {"form": form}
    return render(request, "ticket.html", context)


@login_required
def create_review(request):
    """Create a ticket and its review in the same time."""
    if request.method == "POST":
        form_ticket = TicketForm(request.POST, request.FILES)
        if form_ticket.is_valid():
            ticket = form_ticket.save(commit=False)
            ticket.user = request.user
            ticket.save()
            form_review = ReviewForm(request.POST)
            if form_review.is_valid():
                review = form_review.save(commit=False)
                review.ticket = ticket
                review.user = request.user
                review.save()
            return redirect("board:posts")
    else:
        form_ticket = TicketForm()
        form_review = ReviewForm()
    context = {"form_ticket": form_ticket, "form_review": form_review}
    return render(request, "review.html", context)


@login_required
def add_comment(request, ticket_id):
    """Add a review to a ticket."""
    instance_ticket = Ticket.objects.get(id=ticket_id)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.ticket = instance_ticket
            comment.save()
            return redirect("board:flux")
    else:
        form = ReviewForm()
    context = {"form": form, "ticket": instance_ticket}
    return render(request, "comment.html", context)


@login_required
def delete_review(request, review_id):
    """Delete a review."""
    review = Review.objects.get(id=review_id)
    if request.user == review.user:
        review.delete()
    return redirect("board:posts")


@login_required
def update_review(request, review_id):
    """Update a review."""
    instance_review = Review.objects.get(id=review_id)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=instance_review)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            return redirect("board:flux")
    else:
        form = ReviewForm(instance=instance_review)
    context = {"form": form}
    return render(request, "comment.html", context)

board/templates/base_board.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}LITReview{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<header>
    <nav nav class="navbar navbar-dark bg-primary">
        <div class=" navigation bg-light border rounded 2px fixed-top">
            <div class="row ">
                <div class="col-lg-7 text-right">
                    <h3 class="mr-4">LITReview</h3>
                </div>
                <div class=" menu col-lg-5 text-right mt-2">
                    <a class="mr-3 font-weight-bold"> {{ user.username|capfirst }}</a>
                    <a class="mr-3" href="{% url 'board:flux' %}">Flux</a>
                    <a class="mr-3" href="{% url 'board:posts' %}">Posts</a>
                    <a class="mr-3" href="{% url 'follow:follow' %}">Abonnements</a>
                    <a class="mr-3 text-muted" href="{% url 'login:logout' %}">Déconnexion</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<body class="body">
    <div class="container-fluid mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

board/templates/comment.html
{% extends 'base_board.html' %}

{% block content %}
<div class="row d-flex justify-content-center ">
    <h2>Répondre une critique</h2>
</div>
<div class="row d-flex justify-content-center py-2">
    <article class="col-lg-6">
        <div class="border rounder 3px bg-light mt-4 px-3 py-2">
            <span class="font-italic">Vous êtes en train de répondre à {{ ticket.user.username|capfirst }}
            </span>
            <div class="border rounder 3px bg-white my-4 px-3 py-4">
                <div class="box text-center">
                    <h5 class="font-weight-bold">
                        {{ ticket.title }}
                    </h5>
                </div>
                <div class="text-center">
                    {{ ticket.description|safe }}
                </div>
            </div>
            {% if form.review.id %}
                <form class="font-weight-bold" method="POST">
            {% else %}
                <form class="font-weight-bold" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class=" text-right">
                        <input class="btn btn-success" type="submit" value="Envoyer">
                    </div>
                </form>
            {% endif %}
        </div>
    </article>
</div>
{% endblock %}

board/templates/flux.html
{% extends 'base_board.html' %}


{% block content %}
{% if not tickets %}
    <div class="row d-flex justify-content-center py-2">
        <p class="font-weight-bold">Les utilisateurs qu vous suivez n'ont pas encore écrit.</p>
    </div>
{% else %}
    {% for ticket in tickets %}
        <div class="row d-flex justify-content-center py-2">
            <div class="col-lg-6">
                <div class="flux border border-secondary rounded mt-4 px-3 py-2">
                    <p><span class="font-weight-bold">{{ ticket.user.username|capfirst }} a demandé une critique</span>
                        <span class="font-weight-light">{{ ticket.time_created }}</span>
                    </p>
                    <div class="box text-center">
                        <h5 class="font-weight-bold">
                            {{ ticket.title }}
                        </h5>
                    </div>
                    <div class="container pt-3">
                        <div class="row">
                            {% if ticket.image %}
                                <div class="col flex-grow-0 px-1">
                                    <img src="{{ ticket.image.url }}" width="140" height="140" alt="{{ticket.title}}" />
                                </div>
                            {% endif %}
                            <div class="col-9 text-justify">
                                {{ ticket.description|safe }}
                            </div>
                        </div>
                    </div>
                    <div>
                        {% if not ticket.review_set.all %}
                            {% if ticket.user == user %}
                               <div class="text-right">
                                    <a type="button" href="{% url 'board:update_ticket' ticket.id %}">
                                    Modifier
                                    </a>
                                    <a class="text-warning" href="{% url 'board:delete_ticket' ticket.id %}"
                                     onclick="return confirm('Etes-vous sur de vouloir supprimer ?')">
                                    Supprimer
                                    </a>
                                </div>
                            {% else %}
                                <div class="text-right">
                                    <a class="button" href="{% url 'board:comment' ticket.id %}">
                                        Répondre
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                        {% for review in ticket.review_set.all %}
                            <div class="ticket border rounder 3px bg-light mt-4 pl-3 pr-3 py-2">
                                <p><span class="font-weight-bold">Critique publiée par {{ review.user.username|capfirst }}</span>
                                    <span class="font-weight-light">{{ review.time_created }}</span>
                                </p>
                                <div class="box text-center">
                                    <h5>{{ review.headline }}</h5>
                                </div>
                                <div class="box">
                                    {{ review.body }}
                                </div>
                                <div class="box pt-2">
                                    <h5>Note : {{ review.rating }}<span class="text-warning">&#9733</span></h5>
                                </div>
                                {% if review.user == user %}
                                    <div class="text-right">
                                        <a type="button" href="{% url 'board:update_review' review.id %}">
                                            Modifier
                                        </a>
                                        <a class="text-warning" href="{% url 'board:delete_review' review.id %}"
                                            onclick="return confirm('Etes-vous sur de vouloir supprimer ?')">
                                            Supprimer
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

board/templates/posts.html
{% extends 'base_board.html' %}


{% block content %}
<div class="row d-flex justify-content-center ">
    <h2>Vos publications</h2>
</div>

<div class="container text-center">
    <a class="btn btn-light" href="{% url 'board:ticket' %}" type="button ">
        Demander une critique
    </a>
    <a class="btn btn-light" href="{% url 'board:review' %}" type="button">
        Ecrire une critique
    </a>
</div>

{% if not tickets %}
    <div class="row d-flex justify-content-center py-2">
        <p class="font-weight-bold">Vous n'avez encore rien publié.</p>
    </div>
{% else %}
    {% for ticket in tickets %}
    <div class="row d-flex justify-content-center py-2">
        <div class="col-lg-6">
            <div class="border border-secondary rounded mt-4 px-3 py-2">
                <p>
                    <span class="font-weight-bold">Ticket publié le </span>
                    <span class="font-weight-light">{{ ticket.time_created }}</span>
                </p>
                <div class="box text-center">
                    <h5 class="font-weight-bold">
                        {{ ticket.title }}
                    </h5>
                </div>
                <div class="container pt-3">
                    <div class="row">
                    {% if ticket.image %}
                            <div class="col flex-grow-0 px-1">
                                <img src="{{ ticket.image.url }}" width="140" height="140" alt="{{ticket.title}}" />
                            </div>
                        {% endif %}
                        <div class="col-9 text-justify">
                            {{ ticket.description|safe }}
                        </div>
                    </div>
                </div>
                <div class="text-right">
                    <a type="button" href="{% url 'board:update_ticket' ticket.id %}">
                    Modifier
                    </a>
                    <a class="text-warning" href="{% url 'board:delete_ticket' ticket.id %}"
                        onclick="return confirm('Etes-vous sur de vouloir supprimer ?')">
                        Supprimer
                    </a>
                </div>
                <div>
                    {% for review in ticket.review_set.all %}
                        <div class="border rounder 3px bg-light mt-4 px-3 py-2">
                            <p><span class="font-weight-bold">Critique publiée par {{ review.user.username|capfirst }}
                                </span>
                                <span class="font-weight-light"> le {{ review.time_created }}</span>
                            </p>
                            <div class="box text-center">
                                <h5>{{ review.headline }}</h5>
                            </div>
                            <div class="box">
                                {{ review.body }}
                            </div>
                            <div class="box pt-2">
                                <h5>Note : {{ review.rating }}<span class="text-warning">&#9733</span></h5>
                            </div>
                            {% if review.user == user %}
                                <div class="text-right">
                                    <a type="button" href="{% url 'board:update_review' review.id %}">
                                        Modifier
                                    </a>
                                    <a class="text-warning" href="{% url 'board:delete_review' review.id %}"
                                        onclick="return confirm('Etes-vous sur de vouloir supprimer ?')">
                                        Supprimer
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

board/templates/review.html
{% extends 'base_board.html' %}


{% block content %}
<div class="row d-flex justify-content-center ">
    <h2>Ecrire une critique complète</h2>
</div>
<div class="row d-flex justify-content-center py-2">
    <article class="col-lg-6">
        <div class="border rounder 3px bg-light mt-4 px-3 py-2">
            <form class="font-weight-bold" method="POST" action="{% url 'board:review' %}">
                {% csrf_token %}
                {{ form_ticket.as_p}}
                {{form_review.as_p}}
                <div class="text-right">
                    <input class="btn btn-success" type="submit" value="Envoyer">
                </div>
            </form>
        </div>
    </article>
</div>

{% endblock %}

board/templates/ticket.html
{% extends 'base_board.html' %}


{% block content %}
<div class="row d-flex justify-content-center ">
    <h2>Demander une critique</h2>
</div>
<div class="row d-flex justify-content-center py-2">
    <article class="col-lg-6">
        <div class="border rounder 3px bg-light mt-4 px-3 py-2">
            {% if form.ticket.id %}
                <form class="form-group" method="POST" enctype="multipart/form-data" action="">
            {% else %}
                <form class=" form-group" method="POST" enctype="multipart/form-data" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-right">
                        <input class="btn btn-success" type="submit" value="Envoyer">
                    </div>
                </form>
            {% endif %}
        </div>
    </article>
</div>
{% endblock %}