board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "board"

urlpatterns = [
    path("flux/", views.display_flux, name="flux"),
    path("posts/", views.display_posts, name="posts"),
    path("review/", views.create_review, name="review"),
    path("comment/<str:ticket_id>", views.add_comment, name="comment"),
    path("delete_review/<str:review_id>", views.delete_review, name="delete_review"),
    path("update_review/<str:review_id>", views.update_review, name="update_review"),
    path("ticket/", views.create_ticket, name="ticket"),
    path("update_ticket/<str:ticket_id>", views.update_ticket, name="update_ticket"),
    path("delete_ticket/<str:ticket_id>", views.delete_ticket, name="delete_ticket"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("login.urls")),
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("board/follow/", include("follow.urls")),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views


app_name = "login"

urlpatterns = [
    path("", views.signin, name="index"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logOut, name="logout"),
]

login/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def signup(request):
    """Create a user account."""
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("login:index")
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {"form": form})


def signin(request):
    "Log into a user account."
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("board:flux")
    else:
        form = AuthenticationForm()
    return render(request, "index.html", {"form": form})


def logOut(request):
    "Disconnect from an user account."
    if request.user.is_authenticated:
        logout(request)
    return redirect("login:index")

login/templates/base_login.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}LITReview{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<header>
    <div class="container-fluid">
        <div class="navigation bg-light border rounded 2px fixed-top ">
            <div class="mx-auto" style="width: 200px;">
                <h3 class="mr-6">LITReview</h3>
            </div>
        </div>
    </div>
    </div>
</header>

<body class="body">
    <div class="container-fluid mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

login/templates/index.html
{%extends 'base_login.html'%}


{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 pt-4">
        <div class="card">
            <div class="card-body text-center">
                <h3 class="card-title">Connectez-vous</h3>
                <form class="signin" method="POST" action="{% url 'login:index' %}">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input class="btn btn-primary fit" type="submit" value="Se connecter">
                </form>
            </div>
            <div class="card-footer text-center">
                Inscrivez-vous maintenant <a href="{% url 'login:signup' %}" class="button primary fit">S'inscrire</a>
            </div>
        </div>
        <div class="text-center py-2">
            <small>
                <a class="text-muted" href="#">Mot de passe oublié ?</a>
            </small>
        </div>
    </div>
</div>
{% endblock %}

login/templates/signup.html
{%extends 'base_login.html'%}


{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8 pt-4">
        <div class="card">
            <div class="card-body text-center">
                <h3 class="card-title">Inscrivez-vous</h3>
                <form class="signup" method="POST" action="{% url 'login:signup' %}">
                    {% csrf_token %}
                    {{ form.as_p}}
                    <a class="button text-muted" href="{% url 'login:index' %}">Retour</a>
                    <input class="btn btn-primary" type="submit" value="S'inscrire"
                        onclick="return confirm('Votre compte est bien enregistré')">
                    {% if messages %}
                    {% for message in messages %}
                    <p class="text-danger"> {{message}}</p>
                    {% endfor %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}