board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "board"

urlpatterns = [
    path("flux/", views.display_flux, name="flux"),
    path("posts/", views.display_posts, name="posts"),
    path("review/", views.create_review, name="review"),
    path("comment/<str:ticket_id>", views.add_comment, name="comment"),
    path("delete_review/<str:review_id>", views.delete_review, name="delete_review"),
    path("update_review/<str:review_id>", views.update_review, name="update_review"),
    path("ticket/", views.create_ticket, name="ticket"),
    path("update_ticket/<str:ticket_id>", views.update_ticket, name="update_ticket"),
    path("delete_ticket/<str:ticket_id>", views.delete_ticket, name="delete_ticket"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

follow/urls.py
from django.urls import path

from . import views

app_name = "follow"


urlpatterns = [
    path("", views.followup, name="follow"),
    path("unfollow/<user_to_unfollow>", views.unfollow, name="unfollow"),
]

litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("login.urls")),
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("board/follow/", include("follow.urls")),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

follow/models.py
from django.db import models
from django.conf import settings


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following"
    )
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="followed_by",
    )

    class Meta:
        unique_together = ("user", "followed_user")

follow/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render, redirect

from .models import UserFollows


@login_required
def followup(request):
    """Add users to subscription function."""
    context = {"user_follows": UserFollows.objects.all()}
    if request.method == "POST":
        username_to_follow = request.POST.get("username")
        try:
            new_followed = User.objects.get(username=username_to_follow)
        except User.DoesNotExist:
            messages.info(request, "Utilisateur inconnu !")
        else:
            if new_followed == request.user:
                messages.info(request, "Impossible !")
            else:
                try:
                    followed = UserFollows(
                        user=request.user, followed_user=new_followed
                    )
                    followed.save()
                except IntegrityError:
                    messages.info(request, "Vous etes déjà abonnés à cet utilisateur !")
    return render(request, "follow.html", context)


@login_required
def unfollow(request, user_to_unfollow):
    """Unsubscribe users function."""
    user_to_unfollow = User.objects.get(username=user_to_unfollow)
    for followed in UserFollows.objects.all():
        if (followed.user, followed.followed_user) == (request.user, user_to_unfollow):
            followed.delete()
    return redirect("follow:follow")

follow/templates/follow.html
{% extends 'base_board.html' %}


{% block content %}
<div class="row d-flex justify-content-center py-2">
    <div class="col-lg-6">
        <div class="container">
            <ol class="breadcrumb my-4">
                <li class="breadcrumb-item mt-2">Rechercher d'autres utilisateurs</li>
                <div class="col">
                    <form method="POST" action="{% url 'follow:follow' %}">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <input class="form-control col-7" type="text" name="username" width="30"
                                placeholder="Nom d'utilisateur" required>
                            <input class="btn btn-primary col-4 ml-1" type="submit" value="S'abonner" />
                        </div>
                        {% if messages %}
                            {% for message in messages %}
                                <p class="text-danger"> {{ message }}</p>
                            {% endfor %}
                        {% endif %}
                    </form>
                </div>
            </ol>
        </div>
        <div class="container">
            <ol class="breadcrumb my-4">
                <li class="breadcrumb-item active-color">Abonnements</li>
            </ol>
            <table class="table">
                <thead class="thead-inverse">
                    <tr class="text-center">
                        <th>Utilisateurs</th>
                        <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    {% for followed in user_follows %}
                        {% if followed.user == user %}
                            <tr>
                                <td class="col-10 border rounder">{{ followed.followed_user.username|capfirst }}
                                </td>
                                <td class="col-2 border rounder">
                                    <a class="btn btn-danger" type="submit"
                                        href="{% url 'follow:unfollow' followed.followed_user %}"
                                        onclick="return confirm('Etes-vous sur de vous désabonner ?')">Se
                                        désabonner</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container">
            <ol class="breadcrumb my-4">
                <li class="breadcrumb-item active-color">Abonnés</li>
            </ol>
            <table class="table">
                <tbody>
                    {% for followed in user_follows %}
                        {% if followed.followed_user == user %}
                            <tr>
                                <td class="border rounder">{{ followed.user.username|capfirst }}</td>
                            </tr>
                        {% elif followed.followed_user == None %}
                            <tr>
                                <td class="border rounder">Pas d'abonnés</td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}